create table if not exists public.rsvps (
 id bigint generated by default as identity primary key,
 name text not null,
 attendance text not null,
 guests integer not null default 1,
 message text,
 created_at timestamptz not null default now()
);
alter table public.rsvps enable row level security;
-- Only the server-side service role inserts RSVPs; do not expose the service role key to the browser.
